//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IConverter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IConverter.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AED - Emirati Dirham.
        /// </summary>
        public static string @__AED_Emirati_Dirham {
            get {
                return ResourceManager.GetString("__AED_Emirati_Dirham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFN - Afghan Afghani.
        /// </summary>
        public static string @__Afghan_Afghani {
            get {
                return ResourceManager.GetString("__Afghan_Afghani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL - Albanian Lek.
        /// </summary>
        public static string @__Albanian_Lek {
            get {
                return ResourceManager.GetString("__Albanian_Lek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DZD - Algerian Dinar.
        /// </summary>
        public static string @__Algerian_Dinar {
            get {
                return ResourceManager.GetString("__Algerian_Dinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOA - Angolan Kwanza.
        /// </summary>
        public static string @__Angolan_Kwanza {
            get {
                return ResourceManager.GetString("__Angolan_Kwanza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARS - Argentine Peso.
        /// </summary>
        public static string @__Argentine_Peso {
            get {
                return ResourceManager.GetString("__Argentine_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMD - Armenian Dram.
        /// </summary>
        public static string @__Armenian_Dram {
            get {
                return ResourceManager.GetString("__Armenian_Dram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWG - Aruban or Dutch Guilder.
        /// </summary>
        public static string @__Aruban_or_Dutch_Guilder {
            get {
                return ResourceManager.GetString("__Aruban_or_Dutch_Guilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUD - Australian Dollar.
        /// </summary>
        public static string @__AUD_Australian_Dollar {
            get {
                return ResourceManager.GetString("__AUD_Australian_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AZN - Azerbaijani New Manat.
        /// </summary>
        public static string @__Azerbaijani_New_Manat {
            get {
                return ResourceManager.GetString("__Azerbaijani_New_Manat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSD - Bahamian Dollar.
        /// </summary>
        public static string @__Bahamian_Dollar {
            get {
                return ResourceManager.GetString("__Bahamian_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHD - Bahraini Dinar.
        /// </summary>
        public static string @__Bahraini_Dinar {
            get {
                return ResourceManager.GetString("__Bahraini_Dinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BDT - Bangladeshi Taka.
        /// </summary>
        public static string @__Bangladeshi_Taka {
            get {
                return ResourceManager.GetString("__Bangladeshi_Taka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBD - Barbadian or Bajan Dollar.
        /// </summary>
        public static string @__Barbadian_or_Bajan_Dollar {
            get {
                return ResourceManager.GetString("__Barbadian_or_Bajan_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSL - Basotho Loti.
        /// </summary>
        public static string @__Basotho_Loti {
            get {
                return ResourceManager.GetString("__Basotho_Loti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYR - Belarusian Ruble.
        /// </summary>
        public static string @__Belarusian_Ruble {
            get {
                return ResourceManager.GetString("__Belarusian_Ruble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BZD - Belizean Dollar.
        /// </summary>
        public static string @__Belizean_Dollar {
            get {
                return ResourceManager.GetString("__Belizean_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMD - Bermudian Dollar.
        /// </summary>
        public static string @__Bermudian_Dollar {
            get {
                return ResourceManager.GetString("__Bermudian_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTN - Bhutanese Ngultrum.
        /// </summary>
        public static string @__Bhutanese_Ngultrum {
            get {
                return ResourceManager.GetString("__Bhutanese_Ngultrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOB - Bolivian Boliviano.
        /// </summary>
        public static string @__Bolivian_Boliviano {
            get {
                return ResourceManager.GetString("__Bolivian_Boliviano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAM - Bosnian Convertible Marka.
        /// </summary>
        public static string @__Bosnian_Convertible_Marka {
            get {
                return ResourceManager.GetString("__Bosnian_Convertible_Marka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BWP - Botswana Pula.
        /// </summary>
        public static string @__Botswana_Pula {
            get {
                return ResourceManager.GetString("__Botswana_Pula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRL - Brazilian Real.
        /// </summary>
        public static string @__Brazilian_Real {
            get {
                return ResourceManager.GetString("__Brazilian_Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BND - Bruneian Dollar.
        /// </summary>
        public static string @__Bruneian_Dollar {
            get {
                return ResourceManager.GetString("__Bruneian_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGN - Bulgarian Lev.
        /// </summary>
        public static string @__Bulgarian_Lev {
            get {
                return ResourceManager.GetString("__Bulgarian_Lev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMK - Burmese Kyat.
        /// </summary>
        public static string @__Burmese_Kyat {
            get {
                return ResourceManager.GetString("__Burmese_Kyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIF - Burundian Franc.
        /// </summary>
        public static string @__Burundian_Franc {
            get {
                return ResourceManager.GetString("__Burundian_Franc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD - Canadian Dollar.
        /// </summary>
        public static string @__CAD_Canadian_Dollar {
            get {
                return ResourceManager.GetString("__CAD_Canadian_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHR - Cambodian Riel.
        /// </summary>
        public static string @__Cambodian_Riel {
            get {
                return ResourceManager.GetString("__Cambodian_Riel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVE - Cape Verdean Escudo.
        /// </summary>
        public static string @__Cape_Verdean_Escudo {
            get {
                return ResourceManager.GetString("__Cape_Verdean_Escudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KYD - Caymanian Dollar.
        /// </summary>
        public static string @__Caymanian_Dollar {
            get {
                return ResourceManager.GetString("__Caymanian_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAF - Central African CFA Franc BEAC.
        /// </summary>
        public static string @__Central_African_CFA_Franc_BEAC {
            get {
                return ResourceManager.GetString("__Central_African_CFA_Franc_BEAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOF - CFA Franc.
        /// </summary>
        public static string @__CFA_Franc {
            get {
                return ResourceManager.GetString("__CFA_Franc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPF - CFP Franc.
        /// </summary>
        public static string @__CFP_Franc {
            get {
                return ResourceManager.GetString("__CFP_Franc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHF - Swiss Franc.
        /// </summary>
        public static string @__CHF_Swiss_Franc {
            get {
                return ResourceManager.GetString("__CHF_Swiss_Franc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLP - Chilean Peso.
        /// </summary>
        public static string @__Chilean_Peso {
            get {
                return ResourceManager.GetString("__Chilean_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNY - Chinese Yuan Renminbi.
        /// </summary>
        public static string @__CNY_Chinese_Yuan_Renminbi {
            get {
                return ResourceManager.GetString("__CNY_Chinese_Yuan_Renminbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COP - Colombian Peso.
        /// </summary>
        public static string @__Colombian_Peso {
            get {
                return ResourceManager.GetString("__Colombian_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMF - Comoran Franc.
        /// </summary>
        public static string @__Comoran_Franc {
            get {
                return ResourceManager.GetString("__Comoran_Franc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDF - Congolese Franc.
        /// </summary>
        public static string @__Congolese_Franc {
            get {
                return ResourceManager.GetString("__Congolese_Franc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC - Costa Rican Colon.
        /// </summary>
        public static string @__Costa_Rican_Colon {
            get {
                return ResourceManager.GetString("__Costa_Rican_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRK - Croatian Kuna.
        /// </summary>
        public static string @__Croatian_Kuna {
            get {
                return ResourceManager.GetString("__Croatian_Kuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUC - Cuban Convertible Peso.
        /// </summary>
        public static string @__Cuban_Convertible_Peso {
            get {
                return ResourceManager.GetString("__Cuban_Convertible_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUP - Cuban Peso.
        /// </summary>
        public static string @__Cuban_Peso {
            get {
                return ResourceManager.GetString("__Cuban_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZK - Czech Koruna.
        /// </summary>
        public static string @__Czech_Koruna {
            get {
                return ResourceManager.GetString("__Czech_Koruna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DKK - Danish Krone.
        /// </summary>
        public static string @__Danish_Krone {
            get {
                return ResourceManager.GetString("__Danish_Krone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DJF - Djiboutian Franc.
        /// </summary>
        public static string @__Djiboutian_Franc {
            get {
                return ResourceManager.GetString("__Djiboutian_Franc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOP - Dominican Peso.
        /// </summary>
        public static string @__Dominican_Peso {
            get {
                return ResourceManager.GetString("__Dominican_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANG - Dutch Guilder.
        /// </summary>
        public static string @__Dutch_Guilder {
            get {
                return ResourceManager.GetString("__Dutch_Guilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XCD - East Caribbean Dollar.
        /// </summary>
        public static string @__East_Caribbean_Dollar {
            get {
                return ResourceManager.GetString("__East_Caribbean_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGP - Egyptian Pound.
        /// </summary>
        public static string @__Egyptian_Pound {
            get {
                return ResourceManager.GetString("__Egyptian_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERN - Eritrean Nakfa.
        /// </summary>
        public static string @__Eritrean_Nakfa {
            get {
                return ResourceManager.GetString("__Eritrean_Nakfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETB - Ethiopian Birr.
        /// </summary>
        public static string @__Ethiopian_Birr {
            get {
                return ResourceManager.GetString("__Ethiopian_Birr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR - Euro.
        /// </summary>
        public static string @__EUR_Euro {
            get {
                return ResourceManager.GetString("__EUR_Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FKP - Falkland Island Pound.
        /// </summary>
        public static string @__Falkland_Island_Pound {
            get {
                return ResourceManager.GetString("__Falkland_Island_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FJD - Fijian Dollar.
        /// </summary>
        public static string @__Fijian_Dollar {
            get {
                return ResourceManager.GetString("__Fijian_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMD - Gambian Dalasi.
        /// </summary>
        public static string @__Gambian_Dalasi {
            get {
                return ResourceManager.GetString("__Gambian_Dalasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP - British Pound.
        /// </summary>
        public static string @__GBP_British_Pound {
            get {
                return ResourceManager.GetString("__GBP_British_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEL - Georgian Lari.
        /// </summary>
        public static string @__Georgian_Lari {
            get {
                return ResourceManager.GetString("__Georgian_Lari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHS - Ghanaian Cedi.
        /// </summary>
        public static string @__Ghanaian_Cedi {
            get {
                return ResourceManager.GetString("__Ghanaian_Cedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIP - Gibraltar Pound.
        /// </summary>
        public static string @__Gibraltar_Pound {
            get {
                return ResourceManager.GetString("__Gibraltar_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAU - Gold Ounce.
        /// </summary>
        public static string @__Gold_Ounce {
            get {
                return ResourceManager.GetString("__Gold_Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTQ - Guatemalan Quetzal.
        /// </summary>
        public static string @__Guatemalan_Quetzal {
            get {
                return ResourceManager.GetString("__Guatemalan_Quetzal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GGP - Guernsey Pound.
        /// </summary>
        public static string @__Guernsey_Pound {
            get {
                return ResourceManager.GetString("__Guernsey_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNF - Guinean Franc.
        /// </summary>
        public static string @__Guinean_Franc {
            get {
                return ResourceManager.GetString("__Guinean_Franc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GYD - Guyanese Dollar.
        /// </summary>
        public static string @__Guyanese_Dollar {
            get {
                return ResourceManager.GetString("__Guyanese_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTG - Haitian Gourde.
        /// </summary>
        public static string @__Haitian_Gourde {
            get {
                return ResourceManager.GetString("__Haitian_Gourde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HNL - Honduran Lempira.
        /// </summary>
        public static string @__Honduran_Lempira {
            get {
                return ResourceManager.GetString("__Honduran_Lempira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKD - Hong Kong Dollar.
        /// </summary>
        public static string @__Hong_Kong_Dollar {
            get {
                return ResourceManager.GetString("__Hong_Kong_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUF - Hungarian Forint.
        /// </summary>
        public static string @__Hungarian_Forint {
            get {
                return ResourceManager.GetString("__Hungarian_Forint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISK - Icelandic Krona.
        /// </summary>
        public static string @__Icelandic_Krona {
            get {
                return ResourceManager.GetString("__Icelandic_Krona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XDR - IMF Special Drawing Rights.
        /// </summary>
        public static string @__IMF_Special_Drawing_Rights {
            get {
                return ResourceManager.GetString("__IMF_Special_Drawing_Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDR - Indonesian Rupiah.
        /// </summary>
        public static string @__Indonesian_Rupiah {
            get {
                return ResourceManager.GetString("__Indonesian_Rupiah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INR - Indian Rupee.
        /// </summary>
        public static string @__INR_Indian_Rupee {
            get {
                return ResourceManager.GetString("__INR_Indian_Rupee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRR - Iranian Rial.
        /// </summary>
        public static string @__Iranian_Rial {
            get {
                return ResourceManager.GetString("__Iranian_Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQD - Iraqi Dinar.
        /// </summary>
        public static string @__Iraqi_Dinar {
            get {
                return ResourceManager.GetString("__Iraqi_Dinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMP - Isle of Man Pound.
        /// </summary>
        public static string @__Isle_of_Man_Pound {
            get {
                return ResourceManager.GetString("__Isle_of_Man_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ILS - Israeli Shekel.
        /// </summary>
        public static string @__Israeli_Shekel {
            get {
                return ResourceManager.GetString("__Israeli_Shekel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMD - Jamaican Dollar.
        /// </summary>
        public static string @__Jamaican_Dollar {
            get {
                return ResourceManager.GetString("__Jamaican_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JEP - Jersey Pound.
        /// </summary>
        public static string @__Jersey_Pound {
            get {
                return ResourceManager.GetString("__Jersey_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOD - Jordanian Dinar.
        /// </summary>
        public static string @__Jordanian_Dinar {
            get {
                return ResourceManager.GetString("__Jordanian_Dinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPY - Japanese Yen.
        /// </summary>
        public static string @__JPY_Japanese_Yen {
            get {
                return ResourceManager.GetString("__JPY_Japanese_Yen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KZT - Kazakhstani Tenge.
        /// </summary>
        public static string @__Kazakhstani_Tenge {
            get {
                return ResourceManager.GetString("__Kazakhstani_Tenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KES - Kenyan Shilling.
        /// </summary>
        public static string @__Kenyan_Shilling {
            get {
                return ResourceManager.GetString("__Kenyan_Shilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWD - Kuwaiti Dinar.
        /// </summary>
        public static string @__Kuwaiti_Dinar {
            get {
                return ResourceManager.GetString("__Kuwaiti_Dinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KGS - Kyrgyzstani Som.
        /// </summary>
        public static string @__Kyrgyzstani_Som {
            get {
                return ResourceManager.GetString("__Kyrgyzstani_Som", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAK - Lao or Laotian Kip.
        /// </summary>
        public static string @__Lao_or_Laotian_Kip {
            get {
                return ResourceManager.GetString("__Lao_or_Laotian_Kip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LVL - Latvian Lat.
        /// </summary>
        public static string @__Latvian_Lat {
            get {
                return ResourceManager.GetString("__Latvian_Lat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LBP - Lebanese Pound.
        /// </summary>
        public static string @__Lebanese_Pound {
            get {
                return ResourceManager.GetString("__Lebanese_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRD - Liberian Dollar.
        /// </summary>
        public static string @__Liberian_Dollar {
            get {
                return ResourceManager.GetString("__Liberian_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LYD - Libyan Dinar.
        /// </summary>
        public static string @__Libyan_Dinar {
            get {
                return ResourceManager.GetString("__Libyan_Dinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTL - Lithuanian Litas.
        /// </summary>
        public static string @__Lithuanian_Litas {
            get {
                return ResourceManager.GetString("__Lithuanian_Litas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOP - Macau Pataca.
        /// </summary>
        public static string @__Macau_Pataca {
            get {
                return ResourceManager.GetString("__Macau_Pataca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MKD - Macedonian Denar.
        /// </summary>
        public static string @__Macedonian_Denar {
            get {
                return ResourceManager.GetString("__Macedonian_Denar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MGA - Malagasy Ariary.
        /// </summary>
        public static string @__Malagasy_Ariary {
            get {
                return ResourceManager.GetString("__Malagasy_Ariary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MWK - Malawian Kwacha.
        /// </summary>
        public static string @__Malawian_Kwacha {
            get {
                return ResourceManager.GetString("__Malawian_Kwacha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVR - Maldivian Rufiyaa.
        /// </summary>
        public static string @__Maldivian_Rufiyaa {
            get {
                return ResourceManager.GetString("__Maldivian_Rufiyaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRO - Mauritanian Ouguiya.
        /// </summary>
        public static string @__Mauritanian_Ouguiya {
            get {
                return ResourceManager.GetString("__Mauritanian_Ouguiya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUR - Mauritian Rupee.
        /// </summary>
        public static string @__Mauritian_Rupee {
            get {
                return ResourceManager.GetString("__Mauritian_Rupee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDL - Moldovan Leu.
        /// </summary>
        public static string @__Moldovan_Leu {
            get {
                return ResourceManager.GetString("__Moldovan_Leu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MNT - Mongolian Tughrik.
        /// </summary>
        public static string @__Mongolian_Tughrik {
            get {
                return ResourceManager.GetString("__Mongolian_Tughrik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAD - Moroccan Dirham.
        /// </summary>
        public static string @__Moroccan_Dirham {
            get {
                return ResourceManager.GetString("__Moroccan_Dirham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZN - Mozambican Metical.
        /// </summary>
        public static string @__Mozambican_Metical {
            get {
                return ResourceManager.GetString("__Mozambican_Metical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MXN - Mexican Peso.
        /// </summary>
        public static string @__MXN_Mexican_Peso {
            get {
                return ResourceManager.GetString("__MXN_Mexican_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYR - Malaysian Ringgit.
        /// </summary>
        public static string @__MYR_Malaysian_Ringgit {
            get {
                return ResourceManager.GetString("__MYR_Malaysian_Ringgit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAD - Namibian Dollar.
        /// </summary>
        public static string @__Namibian_Dollar {
            get {
                return ResourceManager.GetString("__Namibian_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPR - Nepalese Rupee.
        /// </summary>
        public static string @__Nepalese_Rupee {
            get {
                return ResourceManager.GetString("__Nepalese_Rupee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VUV - Ni-Vanuatu Vatu.
        /// </summary>
        public static string @__Ni_Vanuatu_Vatu {
            get {
                return ResourceManager.GetString("__Ni_Vanuatu_Vatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIO - Nicaraguan Cordoba.
        /// </summary>
        public static string @__Nicaraguan_Cordoba {
            get {
                return ResourceManager.GetString("__Nicaraguan_Cordoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGN - Nigerian Naira.
        /// </summary>
        public static string @__Nigerian_Naira {
            get {
                return ResourceManager.GetString("__Nigerian_Naira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPW - North Korean Won.
        /// </summary>
        public static string @__North_Korean_Won {
            get {
                return ResourceManager.GetString("__North_Korean_Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOK - Norwegian Krone.
        /// </summary>
        public static string @__Norwegian_Krone {
            get {
                return ResourceManager.GetString("__Norwegian_Krone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NZD - New Zealand Dollar.
        /// </summary>
        public static string @__NZD_New_Zealand_Dollar {
            get {
                return ResourceManager.GetString("__NZD_New_Zealand_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMR - Omani Rial.
        /// </summary>
        public static string @__Omani_Rial {
            get {
                return ResourceManager.GetString("__Omani_Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKR - Pakistani Rupee.
        /// </summary>
        public static string @__Pakistani_Rupee {
            get {
                return ResourceManager.GetString("__Pakistani_Rupee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPD - Palladium Ounce.
        /// </summary>
        public static string @__Palladium_Ounce {
            get {
                return ResourceManager.GetString("__Palladium_Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAB - Panamanian Balboa.
        /// </summary>
        public static string @__Panamanian_Balboa {
            get {
                return ResourceManager.GetString("__Panamanian_Balboa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGK - Papua New Guinean Kina.
        /// </summary>
        public static string @__Papua_New_Guinean_Kina {
            get {
                return ResourceManager.GetString("__Papua_New_Guinean_Kina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PYG - Paraguayan Guarani.
        /// </summary>
        public static string @__Paraguayan_Guarani {
            get {
                return ResourceManager.GetString("__Paraguayan_Guarani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEN - Peruvian Nuevo Sol.
        /// </summary>
        public static string @__Peruvian_Nuevo_Sol {
            get {
                return ResourceManager.GetString("__Peruvian_Nuevo_Sol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP - Philippine Peso.
        /// </summary>
        public static string @__PHP_Philippine_Peso {
            get {
                return ResourceManager.GetString("__PHP_Philippine_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPT - Platinum Ounce.
        /// </summary>
        public static string @__Platinum_Ounce {
            get {
                return ResourceManager.GetString("__Platinum_Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLN - Polish Zloty.
        /// </summary>
        public static string @__Polish_Zloty {
            get {
                return ResourceManager.GetString("__Polish_Zloty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QAR - Qatari Riyal.
        /// </summary>
        public static string @__Qatari_Riyal {
            get {
                return ResourceManager.GetString("__Qatari_Riyal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RON - Romanian New Leu.
        /// </summary>
        public static string @__Romanian_New_Leu {
            get {
                return ResourceManager.GetString("__Romanian_New_Leu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUB - Russian Ruble.
        /// </summary>
        public static string @__Russian_Ruble {
            get {
                return ResourceManager.GetString("__Russian_Ruble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWF - Rwandan Franc.
        /// </summary>
        public static string @__Rwandan_Franc {
            get {
                return ResourceManager.GetString("__Rwandan_Franc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHP - Saint Helenian Pound.
        /// </summary>
        public static string @__Saint_Helenian_Pound {
            get {
                return ResourceManager.GetString("__Saint_Helenian_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVC - Salvadoran Colon.
        /// </summary>
        public static string @__Salvadoran_Colon {
            get {
                return ResourceManager.GetString("__Salvadoran_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WST - Samoan Tala.
        /// </summary>
        public static string @__Samoan_Tala {
            get {
                return ResourceManager.GetString("__Samoan_Tala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STD - Sao Tomean Dobra.
        /// </summary>
        public static string @__Sao_Tomean_Dobra {
            get {
                return ResourceManager.GetString("__Sao_Tomean_Dobra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR - Saudi Arabian Riyal.
        /// </summary>
        public static string @__SAR_Saudi_Arabian_Riyal {
            get {
                return ResourceManager.GetString("__SAR_Saudi_Arabian_Riyal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPL - Seborgan Luigino.
        /// </summary>
        public static string @__Seborgan_Luigino {
            get {
                return ResourceManager.GetString("__Seborgan_Luigino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEK - Swedish Krona.
        /// </summary>
        public static string @__SEK_Swedish_Krona {
            get {
                return ResourceManager.GetString("__SEK_Swedish_Krona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSD - Serbian Dinar.
        /// </summary>
        public static string @__Serbian_Dinar {
            get {
                return ResourceManager.GetString("__Serbian_Dinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCR - Seychellois Rupee.
        /// </summary>
        public static string @__Seychellois_Rupee {
            get {
                return ResourceManager.GetString("__Seychellois_Rupee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLL - Sierra Leonean Leone.
        /// </summary>
        public static string @__Sierra_Leonean_Leone {
            get {
                return ResourceManager.GetString("__Sierra_Leonean_Leone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAG - Silver Ounce.
        /// </summary>
        public static string @__Silver_Ounce {
            get {
                return ResourceManager.GetString("__Silver_Ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGD - Singapore Dollar.
        /// </summary>
        public static string @__Singapore_Dollar {
            get {
                return ResourceManager.GetString("__Singapore_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBD - Solomon Islander Dollar.
        /// </summary>
        public static string @__Solomon_Islander_Dollar {
            get {
                return ResourceManager.GetString("__Solomon_Islander_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOS - Somali Shilling.
        /// </summary>
        public static string @__Somali_Shilling {
            get {
                return ResourceManager.GetString("__Somali_Shilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRW - South Korean Won.
        /// </summary>
        public static string @__South_Korean_Won {
            get {
                return ResourceManager.GetString("__South_Korean_Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LKR - Sri Lankan Rupee.
        /// </summary>
        public static string @__Sri_Lankan_Rupee {
            get {
                return ResourceManager.GetString("__Sri_Lankan_Rupee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDG - Sudanese Pound.
        /// </summary>
        public static string @__Sudanese_Pound {
            get {
                return ResourceManager.GetString("__Sudanese_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRD - Surinamese Dollar.
        /// </summary>
        public static string @__Surinamese_Dollar {
            get {
                return ResourceManager.GetString("__Surinamese_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SZL - Swazi Lilangeni.
        /// </summary>
        public static string @__Swazi_Lilangeni {
            get {
                return ResourceManager.GetString("__Swazi_Lilangeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYP - Syrian Pound.
        /// </summary>
        public static string @__Syrian_Pound {
            get {
                return ResourceManager.GetString("__Syrian_Pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWD - Taiwan New Dollar.
        /// </summary>
        public static string @__Taiwan_New_Dollar {
            get {
                return ResourceManager.GetString("__Taiwan_New_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TJS - Tajikistani Somoni.
        /// </summary>
        public static string @__Tajikistani_Somoni {
            get {
                return ResourceManager.GetString("__Tajikistani_Somoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TZS - Tanzanian Shilling.
        /// </summary>
        public static string @__Tanzanian_Shilling {
            get {
                return ResourceManager.GetString("__Tanzanian_Shilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THB - Thai Baht.
        /// </summary>
        public static string @__THB_Thai_Baht {
            get {
                return ResourceManager.GetString("__THB_Thai_Baht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP - Tongan Pa&apos;anga.
        /// </summary>
        public static string @__Tongan_Paanga {
            get {
                return ResourceManager.GetString("__Tongan_Paanga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTD - Trinidadian Dollar.
        /// </summary>
        public static string @__Trinidadian_Dollar {
            get {
                return ResourceManager.GetString("__Trinidadian_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRY - Turkish Lira.
        /// </summary>
        public static string @__TRY_Turkish_Lira {
            get {
                return ResourceManager.GetString("__TRY_Turkish_Lira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TND - Tunisian Dinar.
        /// </summary>
        public static string @__Tunisian_Dinar {
            get {
                return ResourceManager.GetString("__Tunisian_Dinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMT - Turkmenistani Manat.
        /// </summary>
        public static string @__Turkmenistani_Manat {
            get {
                return ResourceManager.GetString("__Turkmenistani_Manat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVD - Tuvaluan Dollar.
        /// </summary>
        public static string @__Tuvaluan_Dollar {
            get {
                return ResourceManager.GetString("__Tuvaluan_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UGX - Ugandan Shilling.
        /// </summary>
        public static string @__Ugandan_Shilling {
            get {
                return ResourceManager.GetString("__Ugandan_Shilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAH - Ukrainian Hryvna.
        /// </summary>
        public static string @__Ukrainian_Hryvna {
            get {
                return ResourceManager.GetString("__Ukrainian_Hryvna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UYU - Uruguayan Peso.
        /// </summary>
        public static string @__Uruguayan_Peso {
            get {
                return ResourceManager.GetString("__Uruguayan_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD - US Dollar.
        /// </summary>
        public static string @__USD_US_Dollar {
            get {
                return ResourceManager.GetString("__USD_US_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UZS - Uzbekistani Som.
        /// </summary>
        public static string @__Uzbekistani_Som {
            get {
                return ResourceManager.GetString("__Uzbekistani_Som", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEF - Venezuelan Bolivar.
        /// </summary>
        public static string @__Venezuelan_Bolivar {
            get {
                return ResourceManager.GetString("__Venezuelan_Bolivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VND - Vietnamese Dong.
        /// </summary>
        public static string @__Vietnamese_Dong {
            get {
                return ResourceManager.GetString("__Vietnamese_Dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YER - Yemeni Rial.
        /// </summary>
        public static string @__Yemeni_Rial {
            get {
                return ResourceManager.GetString("__Yemeni_Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZMK - Zambian Kwacha.
        /// </summary>
        public static string @__Zambian_Kwacha {
            get {
                return ResourceManager.GetString("__Zambian_Kwacha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZMW - Zambian Kwacha.
        /// </summary>
        public static string @__Zambian_Kwacha_B {
            get {
                return ResourceManager.GetString("__Zambian_Kwacha_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAR - South African Rand.
        /// </summary>
        public static string @__ZAR_South_African_Rand {
            get {
                return ResourceManager.GetString("__ZAR_South_African_Rand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZWD - Zimbabwean Dollar.
        /// </summary>
        public static string @__Zimbabwean_Dollar {
            get {
                return ResourceManager.GetString("__Zimbabwean_Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Category_Area {
            get {
                return ResourceManager.GetString("Category_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Category_Currency {
            get {
                return ResourceManager.GetString("Category_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Category_Length {
            get {
                return ResourceManager.GetString("Category_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Category_Temperature {
            get {
                return ResourceManager.GetString("Category_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Category_Time {
            get {
                return ResourceManager.GetString("Category_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Category_Volume {
            get {
                return ResourceManager.GetString("Category_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Category_Weight {
            get {
                return ResourceManager.GetString("Category_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acre.
        /// </summary>
        public static string UnitCenverer_Area_Acre {
            get {
                return ResourceManager.GetString("UnitCenverer_Area_Acre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square centimeter.
        /// </summary>
        public static string UnitCenverer_Area_SquareCentimeter {
            get {
                return ResourceManager.GetString("UnitCenverer_Area_SquareCentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square foot.
        /// </summary>
        public static string UnitCenverer_Area_SquareFoot {
            get {
                return ResourceManager.GetString("UnitCenverer_Area_SquareFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square inch.
        /// </summary>
        public static string UnitCenverer_Area_SquareInch {
            get {
                return ResourceManager.GetString("UnitCenverer_Area_SquareInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square kilometer.
        /// </summary>
        public static string UnitCenverer_Area_SquareKilometer {
            get {
                return ResourceManager.GetString("UnitCenverer_Area_SquareKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square meter.
        /// </summary>
        public static string UnitCenverer_Area_SquareMeter {
            get {
                return ResourceManager.GetString("UnitCenverer_Area_SquareMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square micrometer.
        /// </summary>
        public static string UnitCenverer_Area_SquareMicrometer {
            get {
                return ResourceManager.GetString("UnitCenverer_Area_SquareMicrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square mile.
        /// </summary>
        public static string UnitCenverer_Area_SquareMile {
            get {
                return ResourceManager.GetString("UnitCenverer_Area_SquareMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square millimeter.
        /// </summary>
        public static string UnitCenverer_Area_SquareMillimeter {
            get {
                return ResourceManager.GetString("UnitCenverer_Area_SquareMillimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square yard.
        /// </summary>
        public static string UnitCenverer_Area_SquareYard {
            get {
                return ResourceManager.GetString("UnitCenverer_Area_SquareYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centimeter.
        /// </summary>
        public static string UnitConverter_Length_centimeter {
            get {
                return ResourceManager.GetString("UnitConverter_Length_centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foot.
        /// </summary>
        public static string UnitConverter_Length_foot {
            get {
                return ResourceManager.GetString("UnitConverter_Length_foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inch.
        /// </summary>
        public static string UnitConverter_Length_inch {
            get {
                return ResourceManager.GetString("UnitConverter_Length_inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometer.
        /// </summary>
        public static string UnitConverter_Length_kilometer {
            get {
                return ResourceManager.GetString("UnitConverter_Length_kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light year.
        /// </summary>
        public static string UnitConverter_Length_LightYear {
            get {
                return ResourceManager.GetString("UnitConverter_Length_LightYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meter.
        /// </summary>
        public static string UnitConverter_Length_meter {
            get {
                return ResourceManager.GetString("UnitConverter_Length_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to micrometer.
        /// </summary>
        public static string UnitConverter_Length_micrometer {
            get {
                return ResourceManager.GetString("UnitConverter_Length_micrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mile.
        /// </summary>
        public static string UnitConverter_Length_mile {
            get {
                return ResourceManager.GetString("UnitConverter_Length_mile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millimeter.
        /// </summary>
        public static string UnitConverter_Length_millimeter {
            get {
                return ResourceManager.GetString("UnitConverter_Length_millimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nanometer.
        /// </summary>
        public static string UnitConverter_Length_nanometer {
            get {
                return ResourceManager.GetString("UnitConverter_Length_nanometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yard.
        /// </summary>
        public static string UnitConverter_Length_yard {
            get {
                return ResourceManager.GetString("UnitConverter_Length_yard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to celsius.
        /// </summary>
        public static string UnitConverter_Temperature_Celsius {
            get {
                return ResourceManager.GetString("UnitConverter_Temperature_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to farenheit.
        /// </summary>
        public static string UnitConverter_Temperature_Farenheit {
            get {
                return ResourceManager.GetString("UnitConverter_Temperature_Farenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kelvin.
        /// </summary>
        public static string UnitConverter_Temperature_Kelvin {
            get {
                return ResourceManager.GetString("UnitConverter_Temperature_Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string UnitConverter_Time_day {
            get {
                return ResourceManager.GetString("UnitConverter_Time_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string UnitConverter_Time_hour {
            get {
                return ResourceManager.GetString("UnitConverter_Time_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to microsecond.
        /// </summary>
        public static string UnitConverter_Time_microsecond {
            get {
                return ResourceManager.GetString("UnitConverter_Time_microsecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millisecond.
        /// </summary>
        public static string UnitConverter_Time_millisecond {
            get {
                return ResourceManager.GetString("UnitConverter_Time_millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string UnitConverter_Time_minute {
            get {
                return ResourceManager.GetString("UnitConverter_Time_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string UnitConverter_Time_month {
            get {
                return ResourceManager.GetString("UnitConverter_Time_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nanosecond.
        /// </summary>
        public static string UnitConverter_Time_nanosecond {
            get {
                return ResourceManager.GetString("UnitConverter_Time_nanosecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picosecond.
        /// </summary>
        public static string UnitConverter_Time_picosecond {
            get {
                return ResourceManager.GetString("UnitConverter_Time_picosecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string UnitConverter_Time_Second {
            get {
                return ResourceManager.GetString("UnitConverter_Time_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string UnitConverter_Time_week {
            get {
                return ResourceManager.GetString("UnitConverter_Time_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  year.
        /// </summary>
        public static string UnitConverter_Time_year {
            get {
                return ResourceManager.GetString("UnitConverter_Time_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic centimeter.
        /// </summary>
        public static string UnitConverter_Volume_Cubiccentimeter {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_Cubiccentimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic foot.
        /// </summary>
        public static string UnitConverter_Volume_Cubicfoot {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_Cubicfoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic inch.
        /// </summary>
        public static string UnitConverter_Volume_Cubicinch {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_Cubicinch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic kilometer.
        /// </summary>
        public static string UnitConverter_Volume_Cubickilometer {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_Cubickilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic meter.
        /// </summary>
        public static string UnitConverter_Volume_Cubicmeter {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_Cubicmeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic mile.
        /// </summary>
        public static string UnitConverter_Volume_Cubicmile {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_Cubicmile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubi millimeter.
        /// </summary>
        public static string UnitConverter_Volume_Cubicmillimeter {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_Cubicmillimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic yard.
        /// </summary>
        public static string UnitConverter_Volume_Cubicyard {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_Cubicyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallon.
        /// </summary>
        public static string UnitConverter_Volume_gallon {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liter.
        /// </summary>
        public static string UnitConverter_Volume_liter {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_liter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliliter.
        /// </summary>
        public static string UnitConverter_Volume_milliliter {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_milliliter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pint.
        /// </summary>
        public static string UnitConverter_Volume_pint {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_pint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quart.
        /// </summary>
        public static string UnitConverter_Volume_quart {
            get {
                return ResourceManager.GetString("UnitConverter_Volume_quart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atomic mass unit.
        /// </summary>
        public static string UnitConverter_Weight_atomicMassUnit {
            get {
                return ResourceManager.GetString("UnitConverter_Weight_atomicMassUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carrat.
        /// </summary>
        public static string UnitConverter_Weight_carrat {
            get {
                return ResourceManager.GetString("UnitConverter_Weight_carrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gram.
        /// </summary>
        public static string UnitConverter_Weight_gram {
            get {
                return ResourceManager.GetString("UnitConverter_Weight_gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilogram.
        /// </summary>
        public static string UnitConverter_Weight_kilogram {
            get {
                return ResourceManager.GetString("UnitConverter_Weight_kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milligram.
        /// </summary>
        public static string UnitConverter_Weight_milligram {
            get {
                return ResourceManager.GetString("UnitConverter_Weight_milligram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ounce.
        /// </summary>
        public static string UnitConverter_Weight_ounce {
            get {
                return ResourceManager.GetString("UnitConverter_Weight_ounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pound.
        /// </summary>
        public static string UnitConverter_Weight_pound {
            get {
                return ResourceManager.GetString("UnitConverter_Weight_pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ton.
        /// </summary>
        public static string UnitConverter_Weight_ton {
            get {
                return ResourceManager.GetString("UnitConverter_Weight_ton", resourceCulture);
            }
        }
    }
}
