using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IConverter.Converters
{
    class CurrencyCol
    {

        Currency_Data currencyData = new Currency_Data();
        Currency currency = new Currency();



        public ICollection<Currency> getSupportedCurrencies()
        {
            List<Currency> listOfCurrencies = new List<Currency>();

            
            //stOfCurrencies.Add(currency);
            
            currency.Sympol = Currency_Data.Symbol__AED_Emirati_Dirham;  
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Emirati"; 
            currency.Enabled = true;
            currency.Name = "Dirham";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__Afghan_Afghani;  
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Afghan"; 
            currency.Enabled = true;
            currency.Name = "Afghani";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__Albanian_Lek ;  
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =    "Albanian";
            currency.Enabled = true;
            currency.Name = "Lek";
            listOfCurrencies.Add(currency);      
            currency.Sympol =     Currency_Data.Symbol__Algerian_Dinar ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =     "Algeria" ;
            currency.Name = "Dinar";
            currency.Enabled = true; 
            listOfCurrencies.Add(currency);    
            currency.Sympol =     Currency_Data.Symbol__Angolan_Kwanza;  
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =    "Angola"; 
            currency.Enabled = true;
            currency.Name = "Kwanza";
            listOfCurrencies.Add(currency);    
            currency.Sympol =   Currency_Data.Symbol__Argentine_Peso;  
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Argentin" ; 
            currency.Enabled = true;
            currency.Name = "Peso";
            listOfCurrencies.Add(currency);    
            currency.Sympol = Currency_Data.Symbol__Armenian_Dram;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Armenia"; 
            currency.Enabled = true;
            currency.Name = "Dram";
            listOfCurrencies.Add(currency);     
            currency.Sympol = Currency_Data.Symbol__Aruban_or_Dutch_Guilder;  
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Dutch" ;
            currency.Name = "Guilder";
            currency.Enabled = true;
            listOfCurrencies.Add(currency);        
            currency.Sympol = Currency_Data.Symbol__AUD_Australian_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Australia"; 
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);          
            currency.Sympol = Currency_Data.Symbol__Azerbaijani_New_Manat; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Azerbaijan" ;
            currency.Enabled = true;
            currency.Name = "Manat";
            listOfCurrencies.Add(currency);          
            currency.Sympol =  Currency_Data.Symbol__Bahamian_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Bahamia" ;
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Bahraini_Dinar; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Bahrain";
            currency.Enabled = true;
            currency.Name = "Dinar";
            listOfCurrencies.Add(currency);    
            currency.Sympol =  Currency_Data.Symbol__Bangladeshi_Taka;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Bangladesh"; 
            currency.Enabled = true;
            currency.Name = "Taka";
            listOfCurrencies.Add(currency);  
            currency.Sympol =  Currency_Data.Symbol__Barbadian_or_Bajan_Dollar ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Barbadia"; 
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);      
            currency.Sympol = Currency_Data.Symbol__Basotho_Loti ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Basotho"; 
            currency.Enabled = true; 
            currency.Name = "Loti";
            listOfCurrencies.Add(currency);
            currency.Sympol =  Currency_Data.Symbol__Belarusian_Ruble;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Belarusia" ; 
            currency.Enabled = true;
            currency.Name = "Ruble";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Belizean_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Belizea" ;
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__Bermudian_Dollar; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Bermudia"; 
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Bhutanese_Ngultrum ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Bhutanes" ; 
            currency.Enabled = true; 
            currency.Name = "Ngultrum";
            listOfCurrencies.Add(currency);
            currency.Sympol =  Currency_Data.Symbol__Bolivian_Boliviano; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Bolivia" ; 
            currency.Enabled = true; 
            currency.Name = "Boliviano";
            listOfCurrencies.Add(currency);
            currency.Sympol =  Currency_Data.Symbol__Bosnian_Convertible_Marka;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =   "Bosnia";
            currency.Enabled = true; 
            currency.Name = "Marka";
            listOfCurrencies.Add(currency);      
            currency.Sympol = Currency_Data.Symbol__Botswana_Pula; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Botswan" ;
            currency.Enabled = true;
            currency.Name = "Pula";
            listOfCurrencies.Add(currency);     
            currency.Sympol = Currency_Data.Symbol__Brazilian_Real; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Brazil" ; 
            currency.Enabled = true;
            currency.Name = "Real";
            listOfCurrencies.Add(currency);    
            currency.Sympol = Currency_Data.Symbol__Bruneian_Dollar ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Brunei";
            currency.Enabled = true;
            currency.Name = "Dollar"; 
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__Bulgarian_Lev;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =   "Bulgaria"; 
            currency.Enabled = true; 
            currency.Name = "Lev";
            listOfCurrencies.Add(currency);     
            currency.Sympol =  Currency_Data.Symbol__Burmese_Kyat;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "Burmes";
            currency.Enabled = true;
            currency.Name = "Kyat";
            listOfCurrencies.Add(currency);      
            currency.Sympol = Currency_Data.Symbol__Burundian_Franc ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Burundi";
            currency.Enabled = true;
            currency.Name = "Franc";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__CAD_Canadian_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =    "";
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);            
            currency.Sympol =  Currency_Data.Symbol__Cambodian_Riel;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "";
            currency.Enabled = true; 
            currency.Name = "Riel";
            listOfCurrencies.Add(currency);    
            currency.Sympol =  Currency_Data.Symbol__Cape_Verdean_Escudo ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Cape_Verde" ; 
            currency.Enabled = true;
            currency.Name = "Escudo";
            listOfCurrencies.Add(currency);            
            currency.Sympol = Currency_Data.Symbol__Caymanian_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Caymania"; 
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);  
            currency.Sympol =  Currency_Data.Symbol__Central_African_CFA_Franc_BEAC ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Central Africa";
            currency.Enabled = true; 
            currency.Name = "Franc";
            listOfCurrencies.Add(currency); 
            currency.Sympol = Currency_Data.Symbol__CFA_Franc;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Central Africa";
            currency.Enabled = true;
            currency.Name = "Franc";
            listOfCurrencies.Add(currency);         
            currency.Sympol =  Currency_Data.Symbol__CFP_Franc;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "";
            currency.Enabled = true;
            currency.Name = "Franc";
            listOfCurrencies.Add(currency);         
            currency.Sympol =  Currency_Data.Symbol__CHF_Swiss_Franc ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "";
            currency.Enabled = true;
            currency.Name = "Franc";
            listOfCurrencies.Add(currency);   
            currency.Sympol =   Currency_Data.Symbol__Chilean_Peso ;  
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "Chile";
            currency.Name = "Peso";
            currency.Enabled = true; 
            listOfCurrencies.Add(currency);      
            currency.Sympol = Currency_Data.Symbol__CNY_Chinese_Yuan_Renminbi ; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "China"; 
            currency.Enabled = true;
            currency.Name = "Yuan";
            listOfCurrencies.Add(currency);      
            currency.Sympol =   Currency_Data.Symbol__Colombian_Peso ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =    "Colombia"; 
            currency.Enabled = true;
            currency.Name = "Peso";
            listOfCurrencies.Add(currency);    
            currency.Sympol =   Currency_Data.Symbol__Comoran_Franc;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Comora"; 
            currency.Enabled = true;
            currency.Name = "Franc";
            listOfCurrencies.Add(currency);     
            currency.Sympol =   Currency_Data.Symbol__Congolese_Franc;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "Congo";
            currency.Enabled = true;
            currency.Name = "Franc";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Costa_Rican_Colon ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Costa Rica"; 
            currency.Enabled = true;
            currency.Name = "Colon";
            listOfCurrencies.Add(currency); 
            currency.Sympol =  Currency_Data.Symbol__Croatian_Kuna ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Croatia"; 
            currency.Enabled = true;
            currency.Name = "Kuna";
            listOfCurrencies.Add(currency);     
            currency.Sympol = Currency_Data.Symbol__Cuban_Convertible_Peso;  
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =    "Cuba convertible";
            currency.Enabled = true;
            currency.Name = "Peso";
            listOfCurrencies.Add(currency);         
            currency.Sympol = Currency_Data.Symbol__Cuban_Peso; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =   "Cuba national"; 
            currency.Enabled = true;
            currency.Name = "Peso";
            listOfCurrencies.Add(currency);        
            currency.Sympol =  Currency_Data.Symbol__Czech_Koruna ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "Czech"; 
            currency.Enabled = true;
            currency.Name = "koruna";
            listOfCurrencies.Add(currency);      
            currency.Sympol = Currency_Data.Symbol__Danish_Krone; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =    "Danish"; 
            currency.Enabled = true;
            currency.Name = "Krone";
            listOfCurrencies.Add(currency);      
            currency.Sympol =  Currency_Data.Symbol__Djiboutian_Franc ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Djibouti"; 
            currency.Enabled = true;
            currency.Name = "Franc";
            listOfCurrencies.Add(currency);  
            currency.Sympol =  Currency_Data.Symbol__Dominican_Peso ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Dominic"; 
            currency.Enabled = true;
            currency.Name = "Peso";
            listOfCurrencies.Add(currency);    
            currency.Sympol =  Currency_Data.Symbol__Dutch_Guilder ; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Dutch" ; 
            currency.Enabled = true;
            currency.Name = "Guilder";
            listOfCurrencies.Add(currency); 
            currency.Sympol = Currency_Data.Symbol__East_Caribbean_Dollar ; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "Caribbean"; 
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);          
            currency.Sympol = Currency_Data.Symbol__Egyptian_Pound; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =   "Egypt"; 
            currency.Enabled = true;
            currency.Name = "Pound";
            listOfCurrencies.Add(currency);    
            currency.Sympol = Currency_Data.Symbol__Eritrean_Nakfa; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Eritrea" ;
            currency.Enabled = true;
            currency.Name = "Nakfa";
            listOfCurrencies.Add(currency);    
            currency.Sympol =   Currency_Data.Symbol__Ethiopian_Birr ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "Ethiopia"; 
            currency.Enabled = true;
            currency.Name = "Birr";
            listOfCurrencies.Add(currency);    
            currency.Sympol = Currency_Data.Symbol__EUR_Euro;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "EUR"; 
            currency.Enabled = true;
            currency.Name = "Euro";
            listOfCurrencies.Add(currency);          
            currency.Sympol =  Currency_Data.Symbol__Falkland_Island_Pound;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Falkland Island";
            currency.Enabled = true;
            currency.Name = "Pound";
            listOfCurrencies.Add(currency);          
            currency.Sympol = "Currency_Data.Symbol__Fijian_Dollar";
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =    "Fiji"; 
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);     
            currency.Sympol =  Currency_Data.Symbol__Gambian_Dalasi; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "Gambia";
            currency.Enabled = true; 
            currency.Name = "Dalasi";
            listOfCurrencies.Add(currency);    
            currency.Sympol =  Currency_Data.Symbol__GBP_British_Pound ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Britian"; 
            currency.Enabled = true;
            currency.Name = "Pound";
            listOfCurrencies.Add(currency); 
            currency.Sympol =   Currency_Data.Symbol__Georgian_Lari ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Georgia" ; 
            currency.Enabled = true;
            currency.Name = "Lari";
            listOfCurrencies.Add(currency);     
            currency.Sympol =  Currency_Data.Symbol__Ghanaian_Cedi ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Ghanaia"; 
            currency.Enabled = true;
            currency.Name = "Cedi";
            listOfCurrencies.Add(currency);     
            currency.Sympol = Currency_Data.Symbol__Gibraltar_Pound; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Gibraltar";
            currency.Enabled = true;
            currency.Name = "Pound";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__Gold_Ounce ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Gold"; 
            currency.Enabled = true;
            currency.Name = "Ounce";
            listOfCurrencies.Add(currency);        
            currency.Sympol =   Currency_Data.Symbol__Guatemalan_Quetzal; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Guatemala"; 
            currency.Enabled = true;
            currency.Name = "Quetzal";
            listOfCurrencies.Add(currency);
            currency.Sympol =  Currency_Data.Symbol__Guernsey_Pound;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Guernsey" ;
            currency.Enabled = true;
            currency.Name = "Pound";
            listOfCurrencies.Add(currency);    
            currency.Sympol =  Currency_Data.Symbol__Guinean_Franc;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Guin"; 
            currency.Enabled = true;
            currency.Name = "Franc";
            listOfCurrencies.Add(currency);     
            currency.Sympol =  Currency_Data.Symbol__Guyanese_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Guyana"; 
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__Haitian_Gourde ; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Haiti";
            currency.Enabled = true; 
            currency.Name = "Gourde";
            listOfCurrencies.Add(currency);    
            currency.Sympol =  Currency_Data.Symbol__Honduran_Lempira;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =    "Honduras";
            currency.Enabled = true;
            currency.Name = "Lempira";
            listOfCurrencies.Add(currency);  
            currency.Sympol =  Currency_Data.Symbol__Hong_Kong_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Hong Kong";
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Hungarian_Forint;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Hungary" ;
            currency.Enabled = true; 
            currency.Name = "Forint";
            listOfCurrencies.Add(currency);  
            currency.Sympol =  Currency_Data.Symbol__Icelandic_Krona;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Iceland";
            currency.Enabled = true;
            currency.Name = "Krona";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__IMF_Special_Drawing_Rights ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =   "Special Drawing Rights"; 
            currency.Enabled = false;
            currency.Name = "Rights";
            listOfCurrencies.Add(currency); 
            currency.Sympol =  Currency_Data.Symbol__Indonesian_Rupiah ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Indonesia"; 
            currency.Enabled = true;
            currency.Name = "Rupiah";
            listOfCurrencies.Add(currency); 
            currency.Sympol =  Currency_Data.Symbol__INR_Indian_Rupee ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =   "India"; 
            currency.Enabled = true;
            currency.Name = "Rupee";
            listOfCurrencies.Add(currency);  
            currency.Sympol =  Currency_Data.Symbol__Iranian_Rial ; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =   "Iran";
            currency.Enabled = true;
            currency.Name = "Rial";
            listOfCurrencies.Add(currency);     
            currency.Sympol =  Currency_Data.Symbol__Iraqi_Dinar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Iraq";
            currency.Enabled = true;
            currency.Name = "Dinar";
            listOfCurrencies.Add(currency);       
            currency.Sympol = Currency_Data.Symbol__Isle_of_Man_Pound;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Isle of Man";
            currency.Enabled = true;
            currency.Name = "Pound";
            listOfCurrencies.Add(currency); 
            currency.Sympol =  Currency_Data.Symbol__Israeli_Shekel ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Israel" ;
            currency.Enabled = true;
            currency.Name = "Shekel";
            listOfCurrencies.Add(currency);    
            currency.Sympol = Currency_Data.Symbol__Jamaican_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Jamaica"; 
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__Jersey_Pound; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =   "Jersey"; 
            currency.Enabled = true; 
            currency.Name = "Pound";
            listOfCurrencies.Add(currency);      
            currency.Sympol = Currency_Data.Symbol__Jordanian_Dinar;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Jordan" ; 
            currency.Enabled = true;
            currency.Name = "Dinar";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__JPY_Japanese_Yen;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Japan" ;
            currency.Enabled = true;
            currency.Name = "Yen";
            listOfCurrencies.Add(currency);  
            currency.Sympol =  Currency_Data.Symbol__Kazakhstani_Tenge ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Kazakhstan";
            currency.Enabled = true;
            currency.Name = "Tenge";
            listOfCurrencies.Add(currency); 
            currency.Sympol =  Currency_Data.Symbol__Kenyan_Shilling ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Kenya";
            currency.Enabled = true;
            currency.Name = "Shilling";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__Kuwaiti_Dinar ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Kuwait" ; 
            currency.Enabled = true; 
            currency.Name = "Dinar";
            listOfCurrencies.Add(currency);     
            currency.Sympol = Currency_Data.Symbol__Kyrgyzstani_Som;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Kyrgyzstan";
            currency.Enabled = true;
            currency.Name = "Som";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__Lao_or_Laotian_Kip; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Lao";
            currency.Enabled = true;
            currency.Name = "Kip";    
            listOfCurrencies.Add(currency);
            currency.Sympol =  Currency_Data.Symbol__Latvian_Lat;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "Latvia" ;
            currency.Enabled = true;
            currency.Name = "Lat";
            listOfCurrencies.Add(currency);       
            currency.Sympol = Currency_Data.Symbol__Lebanese_Pound;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Lebanon";
            currency.Enabled = true;
            currency.Name = "Pound";
            listOfCurrencies.Add(currency);    
            currency.Sympol = Currency_Data.Symbol__Liberian_Dollar; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Liberia" ;
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Libyan_Dinar;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Libya" ;
            currency.Enabled = true;
            currency.Name = "Dinar";
            listOfCurrencies.Add(currency);      
            currency.Sympol = Currency_Data.Symbol__Lithuanian_Litas;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Lithuania" ;
            currency.Enabled = true;
            currency.Name = "Litas";
            listOfCurrencies.Add(currency);  
            currency.Sympol =  Currency_Data.Symbol__Macau_Pataca; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Macau";
            currency.Enabled = true;
            currency.Name = "Pataca";
            currency.Name = "Pataca";
            listOfCurrencies.Add(currency);      
            currency.Sympol = Currency_Data.Symbol__Macedonian_Denar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Macedonia";
            currency.Enabled = true;
            currency.Name= "Denar";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Malagasy_Ariary;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Malagas" ;
            currency.Enabled = true; 
            currency.Name = "Ariary";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__Malawian_Kwacha ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Malawi" ; 
            currency.Enabled = true; 
            currency.Name ="Kwacha";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Maldivian_Rufiyaa ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Maldivia" ;
            currency.Enabled = true; 
            currency.Name ="Rufiyaa";
            listOfCurrencies.Add(currency); 
            currency.Sympol =  Currency_Data.Symbol__Mauritanian_Ouguiya ; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Mauritania"; 
            currency.Enabled = true; 
            currency.Name = "Ouguiya";
            listOfCurrencies.Add(currency);            
            currency.Sympol = Currency_Data.Symbol__Mauritian_Rupee ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Mauritia" ; 
            currency.Enabled = true; 
            currency.Name = "Rupee";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__Moldovan_Leu ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Moldova" ; 
            currency.Enabled = true; 
            currency.Name = "Leu";
            listOfCurrencies.Add(currency);      
            currency.Sympol =   Currency_Data.Symbol__Mongolian_Tughrik;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Mongolia" ; 
            currency.Enabled = true; 
            currency.Name = "Tughrik";
            listOfCurrencies.Add(currency); 
            currency.Sympol = Currency_Data.Symbol__Moroccan_Dirham ; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Morocco";
            currency.Enabled = true;  
            currency.Name = "Dirham";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Mozambican_Metical; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Mozambic";
            currency.Enabled = true; 
            currency.Name = "Metical";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__MXN_Mexican_Peso;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Mexico"; 
            currency.Enabled = true;
            currency.Name = "Peso";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__MYR_Malaysian_Ringgit ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Malaysia"; 
            currency.Enabled = true; 
            currency.Name = "Ringgit";
            listOfCurrencies.Add(currency);          
            currency.Sympol = Currency_Data.Symbol__Namibian_Dollar; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Namibian" ;
            currency.Enabled = true; 
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Nepalese_Rupee ; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Nepal" ; 
            currency.Enabled = true;
            currency.Name = "Rupee";
            listOfCurrencies.Add(currency);    
            currency.Sympol =  Currency_Data.Symbol__Ni_Vanuatu_Vatu; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Vanuatu" ;
            currency.Enabled = true; 
            currency.Name = "Vatu";

            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Nicaraguan_Cordoba ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Nicaragua" ;
            currency.Enabled = true; 
            currency.Name = "Cordoba";
            listOfCurrencies.Add(currency);
            currency.Sympol =  Currency_Data.Symbol__Nigerian_Naira;  
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Nigeria";
            currency.Enabled = true;
            currency.Name = "Naira"; 
            listOfCurrencies.Add(currency);    
            currency.Sympol =  Currency_Data.Symbol__North_Korean_Won ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "North Korea"; 
            currency.Enabled = true; 
            currency.Name = "Won";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Norwegian_Krone ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Norway";
            currency.Enabled = true;
            currency.Name = "Krone";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__NZD_New_Zealand_Dollar ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "New Zealand" ;
            currency.Enabled = true; 
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__Omani_Rial ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Omani" ;
            currency.Enabled = true;
            currency.Name = "Rial";
            listOfCurrencies.Add(currency);        
            currency.Sympol =  Currency_Data.Symbol__Pakistani_Rupee;  
            currency.ImagePath = "/Assets/Flags/PAK.png";
            currency.Country =  "Pakistan"; 
            currency.Enabled = true; 
            currency.Name = "Rupee";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Palladium_Ounce ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Palladium";
            currency.Enabled = true;
            currency.Name = "Ounce";            
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Panamanian_Balboa ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Panama" ; 
            currency.Enabled = true; 
            currency.Name = "Balboa";
           
            listOfCurrencies.Add(currency); 
            currency.Sympol =   Currency_Data.Symbol__Papua_New_Guinean_Kina ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Papua New Guinean";
            currency.Enabled = true; 
            currency.Name = "Kina";
            listOfCurrencies.Add(currency);         
            currency.Sympol = Currency_Data.Symbol__Paraguayan_Guarani;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Paraguay";
            currency.Enabled = true;
            currency.Name = "Guarani";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__Peruvian_Nuevo_Sol;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Peru";
            currency.Enabled = true;
            currency.Name = "Nuevo Sol";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__PHP_Philippine_Peso ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Philippine" ;
            currency.Enabled = true;
            currency.Name = "Peso";
            listOfCurrencies.Add(currency);            
            currency.Sympol =  Currency_Data.Symbol__Platinum_Ounce ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Platinum" ;
            currency.Enabled = true; 
            currency.Name = "Ounce";
            listOfCurrencies.Add(currency);    

            currency.Sympol =   Currency_Data.Symbol__Polish_Zloty ; 
            currency.ImagePath = "/Assets/Flags/POL.png";
            currency.Country =  "Poland"; currency.Enabled = true;
            currency.Name = "Zloty";
            listOfCurrencies.Add(currency);      
            currency.Sympol = Currency_Data.Symbol__Qatari_Riyal;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Qatar" ;
            currency.Enabled = true;
            currency.Name = "Riyal";
            listOfCurrencies.Add(currency);      
            currency.Sympol =  Currency_Data.Symbol__Romanian_New_Leu; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Romania";
            currency.Enabled = true; 
            currency.Name = "Leu";
            listOfCurrencies.Add(currency);
            currency.Sympol =  Currency_Data.Symbol__Russian_Ruble;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =   "Russia"; 
            currency.Enabled = true;
            currency.Name = "Ruble";
            listOfCurrencies.Add(currency);     
            currency.Sympol = "Rwanda" ;  
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Rwanda"; 
            currency.Enabled = true; 
            currency.Name = "Franc";
            listOfCurrencies.Add(currency);     
            currency.Sympol =  Currency_Data.Symbol__Saint_Helenian_Pound; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Saint Helen" ;
            currency.Enabled = true; 
            currency.Name = "Pound";
            listOfCurrencies.Add(currency);           
            currency.Sympol =  Currency_Data.Symbol__Salvadoran_Colon;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Salvador"; 
            currency.Enabled = true;
            currency.Name = "Colon";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Samoan_Tala ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Samoa";
            currency.Enabled = true;
            currency.Name = "Tala";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__Sao_Tomean_Dobra;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Sao Tome"; 
            currency.Enabled = true;
            currency.Name = "Dobra";
            listOfCurrencies.Add(currency);   
            currency.Sympol =  Currency_Data.Symbol__SAR_Saudi_Arabian_Riyal ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Saudi Arabia" ; currency.Enabled = true;
            currency.Enabled = true;
            currency.Name = "Riyal";
            listOfCurrencies.Add(currency);        
            currency.Sympol = Currency_Data.Symbol__Seborgan_Luigino ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Seborga"; 
            currency.Enabled = true; 
            currency.Name = "Luigino";
            listOfCurrencies.Add(currency);  
            currency.Sympol =  Currency_Data.Symbol__SEK_Swedish_Krona;  
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Sweden";
            currency.Enabled = true; 
            currency.Name = "Krona";
            listOfCurrencies.Add(currency); 
            currency.Sympol = Currency_Data.Symbol__Serbian_Dinar ;  
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Serbia"; 
            currency.Enabled = true;
            currency.Name = "Dinar";
            listOfCurrencies.Add(currency);     
            currency.Sympol = Currency_Data.Symbol__Seychellois_Rupee;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Seychellois"; 
            currency.Enabled = true; 
            currency.Name = "Rupee";
            listOfCurrencies.Add(currency); 
            currency.Sympol = Currency_Data.Symbol__Sierra_Leonean_Leone; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Sierra Leon";
            currency.Enabled = true;
            currency.Name = "Leone";
            listOfCurrencies.Add(currency);           
            currency.Sympol = Currency_Data.Symbol__Silver_Ounce;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Silver"; 
            currency.Enabled = true;
            currency.Name = "Ounce";
            listOfCurrencies.Add(currency);      
            currency.Sympol =  Currency_Data.Symbol__Singapore_Dollar; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Singapore" ;
            currency.Enabled = true; 
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Solomon_Islander_Dollar;  
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Solomon Island";
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);        
            currency.Sympol = Currency_Data.Symbol__Somali_Shilling; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Somalia";
            currency.Enabled = true; 
            currency.Name = "Shilling";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__South_Korean_Won ;  
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "South Korean";
            currency.Enabled = true;
            currency.Name = "Won";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Sri_Lankan_Rupee;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Sri Lanka";
            currency.Enabled = true; 
            currency.Name = "Rupee";
            listOfCurrencies.Add(currency);  
            currency.Sympol =  Currency_Data.Symbol__Sudanese_Pound ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Sudan";
            currency.Enabled = true;
            currency.Name = "Pound";
            listOfCurrencies.Add(currency);    
            currency.Sympol =Currency_Data.Symbol__Surinamese_Dollar ; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Surinam";
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency); 
            currency.Sympol = Currency_Data.Symbol__Swazi_Lilangeni;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Swaziland";
            currency.Enabled = true;
            currency.Name = "Lilangeni";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Syrian_Pound ; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Syria";
            currency.Enabled = true;
            currency.Name = "Pound";
            listOfCurrencies.Add(currency);      
            currency.Sympol = Currency_Data.Symbol__Taiwan_New_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Taiwan" ;
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency); 
            currency.Sympol = Currency_Data.Symbol__Tajikistani_Somoni;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Tajikistan";
            currency.Enabled = true;
            currency.Name = "Somoni";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__Tanzanian_Shilling;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Tanzania" ; 
            currency.Enabled = true; 
            currency.Name = "Shilling";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__THB_Thai_Baht;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Thailand" ; 
            currency.Enabled = true;
            currency.Name = "Baht";
            listOfCurrencies.Add(currency);     
            currency.Sympol = Currency_Data.Symbol__Tongan_Paanga;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Tonga"; 
            currency.Enabled = true;
            currency.Name = "Paanga";
            listOfCurrencies.Add(currency);     
            currency.Sympol = Currency_Data.Symbol__Trinidadian_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Trinidad";
            currency.Enabled = true; 
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__TRY_Turkish_Lira ; 
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Turky" ;
            currency.Enabled = true;
            currency.Name = "Lira";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Tunisian_Dinar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Tunisia";
            currency.Enabled = true; 
            currency.Name = "Dinar";
            listOfCurrencies.Add(currency);    
            currency.Sympol =  Currency_Data.Symbol__Turkmenistani_Manat;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Turkmenistan" ;
            currency.Enabled = true;
            currency.Name = "Manat";
            listOfCurrencies.Add(currency);            
            currency.Sympol = Currency_Data.Symbol__Tuvaluan_Dollar; 
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Tuvalua" ;
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);   
            currency.Sympol =Currency_Data.Symbol__Ugandan_Shilling ;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country =  "Uganda" ;
            currency.Enabled = true;
            currency.Name = "Shilling";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Ukrainian_Hryvna;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Ukrainia" ;
            currency.Enabled = true;
            currency.Name = "Hryvna";
            listOfCurrencies.Add(currency);  
            currency.Sympol = Currency_Data.Symbol__Uruguayan_Peso;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Uruguay";
            currency.Enabled = true;
            currency.Name = "Peso";
            listOfCurrencies.Add(currency);    
            currency.Sympol = Currency_Data.Symbol__USD_US_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "US";
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency);     
            currency.Sympol = Currency_Data.Symbol__Uzbekistani_Som ;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Uzbekistan";
            currency.Enabled = true;
            currency.Name = "Som";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Venezuelan_Bolivar;
            currency.ImagePath = "/Assets/Flags/USA.png"; 
            currency.Country = "Venezuela"; 
            currency.Enabled = true;
            currency.Name = "Bolivar";
            listOfCurrencies.Add(currency);
            currency.Sympol = Currency_Data.Symbol__Vietnamese_Dong;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Vietnam";
            currency.Enabled = true;
            currency.Name = "Dong";
            listOfCurrencies.Add(currency);   
            currency.Sympol = Currency_Data.Symbol__Yemeni_Rial;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Yemen";
            currency.Enabled = true;
            currency.Name = "Rial";
            listOfCurrencies.Add(currency);       
            currency.Sympol = Currency_Data.Symbol__Zambian_Kwacha;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country =  "Zambia";
            currency.Enabled = true;
            currency.Name = "Kwacha";
            listOfCurrencies.Add(currency);    
 
            currency.Sympol = Currency_Data.Symbol__ZAR_South_African_Rand;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "South Africa" ;
            currency.Enabled = true;
            currency.Name = "Rand";
            listOfCurrencies.Add(currency);         
            currency.Sympol = Currency_Data.Symbol__Zimbabwean_Dollar;
            currency.ImagePath = "/Assets/Flags/USA.png";
            currency.Country = "Zimbabwe";
            currency.Enabled = true;
            currency.Name = "Dollar";
            listOfCurrencies.Add(currency); 
            
            return listOfCurrencies;
        }
        
    }
}
